vrrp_instance VI_LICENSE {
    state BACKUP
    interface eth0
    virtual_router_id 10
    priority 100
    advert_int 1
    virtual_ipaddress {
        192.168.100.10
    }
}

vrrp_instance VI_BACKUP {
    state BACKUP
    interface eth0
    virtual_router_id 20
    priority 100
    advert_int 1
    virtual_ipaddress {
        192.168.100.20
    }
}
